export const metadata = {
  title: "Shop for us",
  description: "Generated by Me",
};
import Header from "@/Components/Header";
import "./globals.css";
import Footer from "@/Components/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" relative">
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
